# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13m4_lqipPH9X1e9c4pPoNIiE_TY08le7
"""

import streamlit as st
import pandas as pd
import joblib
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef, confusion_matrix

# Page Config
st.set_page_config(page_title="ML Classification Dashboard", layout="wide")

# Title and Info
st.title("🔬 ML Classification Model Dashboard")
st.markdown("""
This application demonstrates 6 different classification models trained on the Breast Cancer Wisconsin dataset.
Upload your test data (CSV) to evaluate the models.
""")

# Sidebar
st.sidebar.header("Configuration")

# 1. Dataset Upload
uploaded_file = st.sidebar.file_uploader("Upload CSV (Test Data)", type=["csv"])

# 2. Model Selection
model_options = [
    "Logistic Regression",
    "Decision Tree",
    "KNN",
    "Naive Bayes",
    "Random Forest",
    "XGBoost"
]
selected_model_name = st.sidebar.selectbox("Select Model", model_options)

# Load helper functions
@st.cache_resource
def load_resources():
    scaler = joblib.load('model/scaler.pkl')
    models = {}
    for name in model_options:
        filename = f"model/{name.replace(' ', '_').lower()}.pkl"
        if os.path.exists(filename):
            models[name] = joblib.load(filename)
    return scaler, models

try:
    scaler, loaded_models = load_resources()
except Exception as e:
    st.error(f"Error loading models. Make sure 'train_models.py' has been run. Error: {e}")
    st.stop()

# Main Logic
if uploaded_file is not None:
    try:
        data = pd.read_csv(uploaded_file)
        st.write("### Uploaded Data Preview")
        st.dataframe(data.head())

        # Check if target column exists for evaluation
        # Assuming the target is the last column or named 'target'
        # For this assignment's dataset, we called it 'target' in train_models.py
        target_col = 'target'

        if target_col in data.columns:
            X_test = data.drop(columns=[target_col])
            y_test = data[target_col]
            has_labels = True
        else:
            st.warning(f"Column '{target_col}' not found. Performing prediction only (no metrics).")
            X_test = data
            has_labels = False

        # Preprocessing
        # We must scale the input data if the model requires it
        model = loaded_models[selected_model_name]

        if selected_model_name in ["Logistic Regression", "KNN"]:
            X_input = scaler.transform(X_test)
        else:
            X_input = X_test

        # Prediction
        preds = model.predict(X_input)
        probs = model.predict_proba(X_input)[:, 1]

        # Display Results
        st.write(f"### Results for {selected_model_name}")

        col1, col2 = st.columns([1, 2])

        with col1:
            if has_labels:
                st.subheader("Evaluation Metrics")
                acc = accuracy_score(y_test, preds)
                auc = roc_auc_score(y_test, probs)
                prec = precision_score(y_test, preds)
                rec = recall_score(y_test, preds)
                f1 = f1_score(y_test, preds)
                mcc = matthews_corrcoef(y_test, preds)

                metrics_df = pd.DataFrame({
                    'Metric': ['Accuracy', 'AUC Score', 'Precision', 'Recall', 'F1 Score', 'MCC'],
                    'Value': [acc, auc, prec, rec, f1, mcc]
                })
                st.table(metrics_df.style.format({'Value': '{:.4f}'}))
            else:
                st.info("Upload data with 'target' column to see evaluation metrics.")

        with col2:
            if has_labels:
                st.subheader("Confusion Matrix")
                cm = confusion_matrix(y_test, preds)
                fig, ax = plt.subplots(figsize=(6, 4))
                sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax)
                plt.xlabel('Predicted')
                plt.ylabel('Actual')
                st.pyplot(fig)

        # Show raw predictions
        st.subheader("Raw Predictions")
        results_df = X_test.copy()
        results_df['Predicted_Class'] = preds
        results_df['Prediction_Probability'] = probs
        st.dataframe(results_df)

    except Exception as e:
        st.error(f"Error processing the file. Ensure it matches the training data format. Details: {e}")

else:
    st.info("Please upload a CSV file to begin analysis.")
    st.markdown("For testing, run `train_models.py` locally to generate `test_data_sample.csv`.")